// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles(arg1:string[]):Promise<Array<main.FileItem>>;

export function BrowseFiles():Promise<Array<main.FileItem>>;

export function CancelDownload():Promise<void>;

export function CancelTranscription():Promise<void>;

export function ClearFiles():Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function DownloadModel():Promise<void>;

export function GetLanguages():Promise<Array<main.LangOption>>;

export function IsFFmpegAvailable():Promise<boolean>;

export function IsModelAvailable():Promise<boolean>;

export function RemoveFile(arg1:string):Promise<void>;

export function StartTranscription(arg1:main.TranscriptionConfig):Promise<void>;
