// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function BrowseFiles() {
  return window['go']['main']['App']['BrowseFiles']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelTranscription() {
  return window['go']['main']['App']['CancelTranscription']();
}

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function DownloadModel() {
  return window['go']['main']['App']['DownloadModel']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function IsFFmpegAvailable() {
  return window['go']['main']['App']['IsFFmpegAvailable']();
}

export function IsModelAvailable() {
  return window['go']['main']['App']['IsModelAvailable']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function StartTranscription(arg1) {
  return window['go']['main']['App']['StartTranscription'](arg1);
}
